name: Check

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
  pull_request: ~

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: task composer-validate composer-normalize composer-audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: vendor/bin/php-cs-fixer fix --diff --verbose --dry-run --stop-on-violation --format=checkstyle

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          ini-file: development
          tools: composer:v2
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: task test
